### ISSUE TITLE
flag to silence vex

### ISSUE THREAD

**Issue by sharethewisdom** [briansteffens/vex#1]
hi,
would you like to add a flag to prevent vex to [print](https://github.com/briansteffens/vex/blob/d96f2efc33570299b471480697c9785d27b70406/src/main.rs#L100) the expanded command?

**Comment by briansteffens** [comment]
Thanks for the suggestion! Maybe it should be silent by default and have a verbose flag to show the command?

**Comment by briansteffens** [comment]
Vex is now silent unless --verbose or --dry is specified, closing. Thanks again.
